package dev.usbharu.multim.misskey.v12.model.components

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

@Serializable
data class UserDetailedNotMe(
    val id: String,
    val name: String?,
    val username: String,
    val host: String? = null,
    val avatarUrl: String? = null,
    val avatarBlurhash: String? = null,
    val avatarColor: String? = null,
    val isAdmin: Boolean = false,
    val isModerator: Boolean = false,
    val isBot: Boolean = false,
    val isCat: Boolean = false,
    val emojis: List<EmojiLite> = emptyList(),
    val onlineStatus: String,
    val url: String? = null,
    val uri: String? = null,
    val createdAt: Instant,
    val updatedAt: Instant? = null,
    val lastFetchedAt: Instant? = null,
    val bannerUrl: String? = null,
    val bannerBlurhash: String? = null,
    val bannerColor: String? = null,
    val isLocked: Boolean = false,
    val isSilenced: Boolean = false,
    val isSuspended: Boolean = false,
    val description: String? = null,
    val location: String? = null,
    val birthday: String? = null,
    val lang: String? = null,
    val fields: List<Field> = emptyList(),
    val followersCount: Int = 0,
    val followingCount: Int = 0,
    val notesCount: Int = 0,
    val pinnedNoteIds: List<String> = emptyList(),
    val pinnedNotes: List<Note> = emptyList(),
    val pinnedPageId: String? = null,
    val pinnedPage: Page? = null,
    val publicReactions: Boolean,
    val twoFactorEnabled: Boolean = false,
    val usePasswordLessLogin: Boolean = false,
    val securityKeys: Boolean = false,
    val isFollowing: Boolean? = null,
    val isFollowed: Boolean? = null,
    val hasPendingFollowRequestFromYou: Boolean? = null,
    val hasPendingFollowRequestToYou: Boolean? = null,
    val isBlocking: Boolean? = null,
    val isBlocked: Boolean? = null,
    val isMuted: Boolean? = null
//    val onlineStatus: OnlineStatus,
//    val avatarId: String?,
//    val bannerId: String?,
//    val injectFeaturedNote: Boolean? = null,
//    val receiveAnnouncementEmail: Boolean? = null,
//    val alwaysMarkNsfw: Boolean?,
//    val autoSensitive: Boolean?,
//    val carefulBot: Boolean?,
//    val autoAcceptFollowed: Boolean?,
//    val noCrawle: Boolean?,
//    val isExplorable: Boolean,
//    val isDeleted: Boolean,
//    val hideOnlineStatus: Boolean,
//    val hasUnreadSpecifiedNotes: Boolean,
//    val hasUnreadMentions: Boolean,
//    val hasUnreadAnnouncement: Boolean,
//    val hasUnreadAntenna: Boolean,
//    val hasUnreadChannel: Boolean,
//    val hasUnreadMessagingMessage: Boolean,
//    val hasUnreadNotification: Boolean,
//    val hasPendingReceivedFollowRequest: Boolean,
//    val integrations: Integrations,
//    val mutedWords: List<List<String>>,
//    val mutedInstances: List<String>,
//    val mutingNotificationTypes: List<String>,
//    val emailNotificationTypes: List<String>,
//    val email: String? = null,
//    val emailVerified: Boolean? = null,
//    val securityKeysList: List<SecurityKey>
) : UserDetailed()
